server:
  port: 8080

database:
  host: localhost
  port: 5432
  name: ecomdb
  user: ecomuser
  password: ecompassword
  sslmode: disable

redis:
  host: localhost
  port: 6379

jwt:
  secret: mysecretkey
  access_expiration_mins: 30
  refresh_expiration_days: 7

rabbitmq:
  host: localhost
  port: 5672